name: Deploy the new image

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"] # Must match name in ci.yaml
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Download Argocd Binary
        shell: bash
        run: |
          sudo curl -sSL -o argocd https://argocd-release-server.argocd-ns/download/argocd-linux-amd64
          chmod +x argocd
          cp argocd /usr/local/bin/argocd

      - name: Argocd Login
        shell: bash
        run: |
          argocd login argocd-release-server.argocd-ns --insecure --grpc-web --username admin --password ${{ secrets.ARGOCD_PASSW}}
